baseURL = "https://example.com"
languageCode = "en-us"
title = "Hugo Blog"

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/:filename/"

# feathericons.com sitesinden ikonlar kullanıyoruz
# pre değeri ikon isimlerini temsil ediyor

[menu]
  [[menu.main]]
    name = "Anasayfa"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Etiketler"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  containerMaxWidth = "700px"
  dateFormat = "02.01.2006"
  homeText = "İlk hugo web siteni yaptın, tebrikler :)"